version: "3.9"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    env_file:
      - ./mariadb.env
    environment:
      - TZ=Europe/Paris
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb.env:/mariadb.env
    # For persistant data
    #  - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -p$$MARIADB_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 15

#GLPI Container
  glpi:
    image: flonou/glpi:latest
    container_name : glpi
    hostname: glpi
    depends_on:
      mariadb:
        condition: service_healthy 
    #volumes:
    # For persistant data
    # - /config:/config
    # - /files:/files
    # - /marketplace:/var/www/html/marketplace
    # - /plugins:/var/www/html/plugins
    # To use HTTPS
    # - /ssl:/etc/apache2/ssl
    # or
    # - ./ssl-cert.pem:/etc/apache2/ssl/ssl-cert.pem
    # - ./ssl-cert.key:/etc/apache2/ssl/ssl-cert.key
    #  and optionnaly
    # - ./server-ca.crt:/etc/apache2/ssl/server-ca.crt
    ports:
      - "8080:80"
      - "443:443"
    env_file:
      - ./glpi.env
    environment:
      - TIMEZONE=Europe/Paris
    # To use HTTPS
    #  - ENABLE_HTTPS=true
    # To disable HTTP
    #  - DISABLE_HTTP=true
